services:
  frontend:
    container_name: vue
    image: vueapp:1.0.0
    build:
      context: ./frontend
      dockerfile: dockerfile.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - backend
  backend:
    container_name: fastapi
    image: fastapiapp:1.0.0
    build:
      context: ./backend
      dockerfile: dockerfile.local
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.local
    ports:
      - '8000:8000'
    depends_on:
      - weaviate
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      RERANKER_INFERENCE_API: 'http://reranker-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,reranker-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    container_name: transformer
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-mpnet-base-cos-v1
    environment:
      ENABLE_CUDA: '0'
  reranker-transformers:
    container_name: reranker
    image: cr.weaviate.io/semitechnologies/reranker-transformers:cross-encoder-ms-marco-MiniLM-L-6-v2
    environment:
      ENABLE_CUDA: '0'
volumes:
  weaviate_data:
